# Generated by Django 4.1 on 2023-03-11 14:37

from django.db import migrations, models
import fountain.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Frame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("I", "Image"), ("T", "Text")],
                        default="I",
                        max_length=1,
                    ),
                ),
                ("title", models.CharField(max_length=125)),
                (
                    "orginal_image",
                    models.ImageField(upload_to=fountain.models.image_file_path),
                ),
                (
                    "analyzed_image",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("x_axis", models.IntegerField(default=0)),
                ("y_axis", models.IntegerField(default=0)),
            ],
        ),
    ]
