# Generated by Django 4.1 on 2023-03-12 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fountain", "0002_frame_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField()),
                ("repeat", models.IntegerField(blank=True, default=1, null=True)),
                (
                    "frame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="fountain.frame"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fountain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=125)),
                (
                    "packages",
                    models.ManyToManyField(
                        related_name="packages", to="fountain.package"
                    ),
                ),
            ],
        ),
    ]
