# Generated by Django 4.1 on 2023-03-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fountain", "0003_package_fountain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fountain",
            name="packages",
            field=models.ManyToManyField(
                related_name="fountains", to="fountain.package"
            ),
        ),
    ]
