# Generated by Django 4.1 on 2023-03-12 11:50

from django.db import migrations, models
import fountain.models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("fountain", "0004_alter_fountain_packages"),
    ]

    operations = [
        migrations.AddField(
            model_name="fountain",
            name="code",
            field=models.UUIDField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AddField(
            model_name="fountain",
            name="music",
            field=models.FileField(
                blank=True, null=True, upload_to=fountain.models.music_file_path
            ),
        ),
    ]
