# Generated by Django 4.1 on 2023-03-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fountain", "0008_alter_fountain_packages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fountain",
            name="packages",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="fountains",
                to="fountain.package",
            ),
        ),
    ]
